### ISSUE TITLE
Can't resolve 'fs' in ./node_modules/csv-file-creator/index.js

### ISSUE THREAD

**Issue by dshadgitsystems** [DrPaulBrewer/csv-file-creator#4]
Getting this error when I use it to build AngularJS 6+ applications

**Comment by DrPaulBrewer** [comment]
This code is not actively maintained.

A few suggestions.  These may or may not work:  
* put a try/catch block around calling this code to trap any errors
* make sure `document` and `window` both exist in the environment that is calling this code. Don't use it on web workers.
* try installing a do-nothing shim for module `fs` in your bundler
* try forking this code and removing the `fs` references.  `index.js` is only about 100 lines long and there are only a few spots.
* use someone else's module for this functionality

**Comment by dshadgitsystems** [comment]
Thank you Dr.

Dilshan Jawahar Sha
Software Developer


[cid:image002.png@01D45BD6.F2A1B580]

[cid:image003.png@01D45BD6.F2A1B580]+61 405 678 181<tel:+61405678181>

[cid:image004.png@01D45BD6.F2A1B580] dsha@dgitsystems.com<mailto:dsha@dgitsystems.com>

www.dgitsystems.com<http://www.dgitsystems.com/> | www.telflow.com<http://www.telflow.com>
Melbourne - Australia | Auckland - New Zealand | Bali - Indonesia | Singapore
[cid:image008.jpg@01D45BD6.F2A1B580]

2015 Excellence Award Winner <http://inform.tmforum.org/news/2015/06/tm-forum-names-excellence-awards-winners/>

On 19 Aug 2019, at 12:48 pm, Dr Paul Brewer <notifications@github.com<mailto:notifications@github.com>> wrote:


This code is not actively maintained.

A few suggestions. These may or may not work:

  *   put a try/catch block around calling this code to trap any errors
  *   make sure document and window both exist in the environment that is calling this code. Don't use it on web workers.
  *   install a do-nothing shim for fs
  *   try forking this code and removing the fs references. index.js is only about 100 lines long.
  *   use someone else's module for this functionality
