### ISSUE TITLE
Getting rows[i].join is not a function

### ISSUE THREAD

**Issue by bstark70** [DrPaulBrewer/csv-file-creator#5]
I'm trying to use your code to export a filtered imput csv to a new file and the error handler is saying the "rows[i].join is not a function" in csv-file-creator\index.js:59

**Comment by DrPaulBrewer** [comment]
Sounds like incorrect input data.  

`rows` is your input data; an array-of-arrays is required.   

Then `rows[i]` will be an array, and all arrays have a native join function.  

This is not the best place to post suspected bugs, as my response time may be very long.  If you have a complete code example that doesn't work, you can always try asking on https://stackoverflow.com
